# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wiseSaying' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wiseSaying
  pod 'FSCalendar'

  target 'wiseSayingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wiseSayingUITests' do
    # Pods for testing
  end

end
